language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install Cython==0.29.15
  - pip install scipy==1.2.3
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
